### ISSUE TITLE
Default scan to ignore tests

### ISSUE THREAD

**Issue by binbrain** [morepath/more.jinja2#4]
Seems like instead of the developer needing to do...
config.scan(more.jinja2, ignore=['.tests'])

This prompts to install webtest if you don't have it. You should just be able to...
config.scan(more.jinja2)

**Comment by faassen** [comment]
Besides the discussion about the API, I'm confused how `ignore=['.tests']` makes you install webtest; it should skip the whole test directory.

**Comment by taschini** [comment]
Now closing this issue:
- ``config.scan`` has been removed in Morepath 0.13.
- ``morepath.scan``, which might be thought of as an approximate successor to ``config.scan``, doesn't have to be used with ``more.jinja2``.
- When you actually decide to use ``morepath.scan``, it does ignore the test sub-packages.
